# jekyll configuration

title: "Jekyll-asciidoc-quickstart"

currentVersion: "1.0.4"

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font-awesome
    - hardbreaks!

# end of configuration
